// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo1Lg1244gf1LmZGcdhwU8NjCDcmgGTyQ',
    appId: '1:897683766880:web:efabc453d0ff76a31f8d05',
    messagingSenderId: '897683766880',
    projectId: 'desafio-tecnico-capyba',
    authDomain: 'desafio-tecnico-capyba.firebaseapp.com',
    storageBucket: 'desafio-tecnico-capyba.appspot.com',
    measurementId: 'G-EW152QWFYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ86tbZYjhSrHfyJGIVyqC9dXQgtCXbDo',
    appId: '1:897683766880:android:346d1de3143b4a471f8d05',
    messagingSenderId: '897683766880',
    projectId: 'desafio-tecnico-capyba',
    storageBucket: 'desafio-tecnico-capyba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB05GCOVse-qhqIKmlLISnEzfRbNafU1ck',
    appId: '1:897683766880:ios:e3984c47ef87b11d1f8d05',
    messagingSenderId: '897683766880',
    projectId: 'desafio-tecnico-capyba',
    storageBucket: 'desafio-tecnico-capyba.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseCapybaDesafio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB05GCOVse-qhqIKmlLISnEzfRbNafU1ck',
    appId: '1:897683766880:ios:b27df4587a7c0e201f8d05',
    messagingSenderId: '897683766880',
    projectId: 'desafio-tecnico-capyba',
    storageBucket: 'desafio-tecnico-capyba.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseCapybaDesafio.RunnerTests',
  );
}
